### ISSUE TITLE
Plantage à la fin du niveau 1

### ISSUE THREAD

**Issue by Naoskev** [clementgpro/escape-the-space#1]
Navigateur : chrome.

Erreur :
Uncaught TypeError: Cannot read property 'destroy' of null
PIXI.TilingSprite.destroy @ phaser.js:24092Phaser.TileSprite.destroy @ phaser.js:59789Phaser.Group.removeAll @ phaser.js:34721Phaser.Group.destroy @ phaser.js:34805Phaser.World.shutdown @ phaser.js:35102Phaser.StateManager.clearCurrentState @ phaser.js:30685Phaser.StateManager.preUpdate @ phaser.js:30609Phaser.Game.updateLogic @ phaser.js:39002Phaser.Game.update @ phaser.js:38950Phaser.RequestAnimationFrame.updateRAF @ phaser.js:61958Phaser.RequestAnimationFrame.start._onLoop @ phaser.js:61942

**Comment by clementgpro** [comment]
Problem will be solved when a new level will be released.
(next week)
